### PR TITLE
Support className and style prop for OTPublisher and OTSubscriber

### PR DESCRIPTION
**Pull request by michaellopez**
As discussed in #57 here is an attempt to address the issue of not being able to style the anonymous `div`.

I deliberately did not include a reference to issue 57 in the commit message, as #57 really is about documentation, not this improvement.

### CODE REVIEW

**Comment by michaellopez** [comment]
There is similar support for `style` prop in #30

**Comment by th317erd** [comment]
Shouldn't the `style` PropType instead be `PropTypes.oneOfType([PropTypes.array, PropTypes.object])`?

Also, can we please get this merged?

**Comment by jasonmichaels** [comment]
This proposed PR is very useful -- if the maintainers aren't maintaining the package anymore, I'd like to suggest recruiting help. The review for this PR, locally, works -- it doesn't break existing behavior and should be considered an upgrade. I'm going to fork this repo to use this PR.

**Comment by michaellopez** [comment]
@jasonmichaels I'm not so sure opentok really had any interest support this library to begin with...

**Comment by jasonmichaels** [comment]
@michaellopez that's unfortunate. We could always fork and extend it, and release it on `npm`. There're obviously devs working with this package (roughly 2K/week). You're right, too -- they haven't updated it in more than a year.

**Comment by inlightmedia** [comment]
We forked extended and published it as https://www.npmjs.com/package/@inlightmedia/opentok-react

**Comment by jasonmichaels** [comment]
@inlightmedia -- are you open to PRs? There are some convenience additions I'd like to contribute. Chiefly, extending components to allow for more options that are available in the (actually) well-maintained API docs. But also items similar to what @michaellopez mentioned above.

**Comment by inlightmedia** [comment]
I haven't setup all the travis checks yet because I was hoping they would merge my PR into the main package but I would have no problem with PRs.

**Comment by jasonmichaels** [comment]
Spoke with a coworker about this -- I'm going to work on extending the PR a bit over the next few weeks. Thanks, @inlightmedia.

**Comment by msach22** [comment]
Hi Team, apologies for the delay on this. @allensarmiento will be reviewing this PR so we can merge this in to the main package.

**Comment by msach22** [comment]
I've changed the target branch to dev since we will go into dev first and then merge into master. @michaellopez Could you please update the branch so it's on par with dev?

**Comment by agionfriddo** [comment]
Any news on when this getting merged to master?

**Comment by msach22** [comment]
@agionfriddo Apologies for the delay on this. The tests just passed (there was an issue with Travis). I merged it into dev, I'm waiting for another PR to add session options and as soon as that's sorted, we can merge to master and publish the package.

**Comment by agionfriddo** [comment]
Fantastic, thanks for jumping on this so quickly.

**Pull request merged**
